import Head from 'next/head'
import styles from '../styles/Home.module.css'
import ProjectList from '../components/ProjectList'
import Hero from '../components/Hero'
import Contact from '../components/Contact'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Aswaikar_portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      {/* Hero Section */}
     
      <Hero/>

      {/* Projects Section */}
     
      <h1 id='projects-section' className='text-5xl text-center pt-5 pb-5 font-bold md:bg-gradient-to-b from-pink-50 to-white'>Projects</h1>
      <ProjectList/>
    
      <footer className="min-h-40 bg-gray-700 flex flex-col justify-center items-center">
        <h1 className='text-center md:text-lg text-gray-100 font-bold'>Contact</h1>
        <Contact/>
        <h1 className='text-center text-xs md:text-lg text-gray-400 p-2 border-t-2 border-gray-400'>© Copyright 2022 - Developed by Ashish Sudhir Waikar</h1>
      </footer>
    </div>
  )
}
